# 文件: render.yaml (最终修正版)

services:
  # 1. 我们的 Python Web 服务器
  - type: web
    name: music-player-web
    env: python
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn 'app:create_app()'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.3
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: music-player-db
          property: connectionString
    # Web 服务的存储盘, 用于存放上传的 mp3/pdf 文件
    disk:
      name: uploads-disk
      mountPath: /app/instance/uploads
      sizeGB: 1

  # 2. 我们的 PostgreSQL 数据库
  - type: pserv
    name: music-player-db
    env: postgres
    # --- 【核心修正】 ---
    # 删除了错误的 'properties' 块
    # 使用官方指定的 'postgresMajorVersion' 字段来定义版本
    postgresMajorVersion: 14
    # 数据库服务的存储盘, 用于存放数据库自身的数据
    disk:
      name: postgres-data
      sizeGB: 1
