services:

  - type: web
    name: music-player-web
    env: python
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn 'app:create_app()'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.3
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: music-player-db
          property: connectionString


  - type: pserv
    name: music-player-db 
    env: postgres 
   
    properties:
    - key: max_connections
      value: 100
    - key: postgres_version
      value: 14
  
  disk:
    name: postgres-data
    sizeGB: 1
